branches:
  only:
  - master

assembly_info:
  patch: false

configuration: Release

platform: Any CPU
  
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

# Install .NET Core SDK 1.0 rc4 build 004771
init:
  - ps: (new-object net.webclient).DownloadFile('https://go.microsoft.com/fwlink/?linkid=841686', "c:/dotnet-install.exe")
  - ps: Start-Process c:\dotnet-install.exe -ArgumentList "/install","/quiet" -Wait

build_script:
  - ps: dotnet restore --no-cache
  - ps: dotnet build .\OvChipApi\OvChipApi.csproj -c Release
  
after_build:
  - ps: dotnet pack .\OvChipApi\OvChipApi.csproj -c Release -version %appveyor_build_version% --no-build -o artifacts
  
artifacts:
  - path: .\**\artifacts\*.nupkg

deploy:
  provider: NuGet
  api_key: oy2faddrgt7h4aso7poqw4ix6cj4bbtezmrju2jhydoasa
  skip_symbols: true
  artifact: /.*\.nupkg/